
services:
### PHP Container #########################################
  laravelphp:
    container_name: laravel-php
    hostname: laravel-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /data
    volumes:
      - ./src:/data
    depends_on:
      - laraveldb
      - laravelredis

### NGINX Container #########################################
  laravelnginx:
    container_name: laravel-nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - laravelphp
    ports:
      - 5000:80
    volumes:
      - ./src:/data
      - ./server/virtualhost.conf:/etc/nginx/conf.d/default.conf

### POSTGRESS Container #########################################
  laraveldb:
    container_name: laraveldb
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: palmasaludip_database
      POSTGRES_USER: palmasalud
      POSTGRES_PASSWORD: zVT0bNWGoUwlg516kDiZN8APNtlRPRvz
      PGPASSWORD: zVT0bNWGoUwlg516kDiZN8APNtlRPRvz
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

### Redis Container #########################################
  laravelredis:
    container_name: laravel-redis
    image: redis:5.0
    expose:
      - 6379
    volumes:
      - ./cache:/data

volumes:
  laravel: